"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Circle, MessageCircle, PackageSearch } from "lucide-react";

export default function TrackOrderPage() {
  const [order, setOrder] = useState(null);
  const [number, setNumber] = useState("");
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("purebreed_last_order") || "null"); setOrder(saved); setNumber(saved?.orderNumber || ""); } catch {} }, []);
  const match = order && number.trim().toUpperCase() === order.orderNumber;
  return <div className="container-px py-12 sm:py-16"><div className="mx-auto max-w-2xl"><div className="text-center"><PackageSearch className="mx-auto text-leaf" size={42} /><p className="eyebrow mt-4">Order updates</p><h1 className="section-title mt-2">Track your order</h1><p className="mt-3 text-sm text-ink/55">Enter your Purebreed order number. This device remembers the most recent order placed here.</p></div><div className="card mt-8 p-6"><label className="text-xs font-bold uppercase tracking-wider text-ink/45">Order number</label><input value={number} onChange={(e) => setNumber(e.target.value)} placeholder="PB-YYYYMMDD-0000" className="input-field mt-2 font-mono" />{number && !match && <p className="mt-3 text-sm text-ink/55">We cannot securely display that order on this device. Contact support for a live update.</p>}{match && <div className="mt-7 border-t border-forest/10 pt-6"><div className="flex items-center justify-between"><div><p className="font-mono text-sm font-bold text-forest">{order.orderNumber}</p><p className="mt-1 text-xs text-ink/45">Placed {new Date(order.placedAt).toLocaleDateString("en-BD")}</p></div><span className="rounded-full bg-turmeric-soft px-3 py-1 text-xs font-bold text-turmeric">Pending confirmation</span></div><div className="mt-7 space-y-4">{[[true,"Order placed"],[false,"Confirmed"],[false,"Packed & dispatched"],[false,"Delivered"]].map(([done,label],i)=><div key={label} className="flex items-center gap-3">{done?<CheckCircle2 className="text-leaf" size={21}/>:<Circle className="text-ink/20" size={21}/>}<span className={`text-sm font-semibold ${done?"text-forest":"text-ink/35"}`}>{label}</span></div>)}</div></div>}<a href={`https://wa.me/8801570252667?text=${encodeURIComponent(`Hello Purebreed, please update me on order ${number || ""}`)}`} target="_blank" rel="noreferrer" className="btn-secondary mt-6 w-full"><MessageCircle size={17} /> Get a live update on WhatsApp</a></div></div></div>;
}
