export const DEMO_PRODUCTS = [
  { id: "demo-turmeric", slug: "pure-turmeric-powder", name_en: "Pure Turmeric Powder", name_bn: "বিশুদ্ধ হলুদ গুঁড়া", category: "spices", price: 220, discountPrice: 195, unit: "200g", stock: 32, isActive: true, isRnD: false, description_en: "Vibrant, aromatic turmeric ground in small batches for everyday cooking." },
  { id: "demo-chilli", slug: "red-chilli-powder", name_en: "Red Chilli Powder", name_bn: "লাল মরিচ গুঁড়া", category: "spices", price: 240, unit: "200g", stock: 26, isActive: true, isRnD: false, description_en: "Clean heat, rich colour and a fresh chilli aroma." },
  { id: "demo-cumin", slug: "roasted-cumin-powder", name_en: "Roasted Cumin Powder", name_bn: "ভাজা জিরা গুঁড়া", category: "spices", price: 290, unit: "150g", stock: 18, isActive: true, isRnD: false, description_en: "Warm, nutty cumin roasted and ground for finishing and cooking." },
  { id: "demo-mustard-oil", slug: "cold-pressed-mustard-oil", name_en: "Cold-Pressed Mustard Oil", name_bn: "ঘানি ভাঙা সরিষার তেল", category: "oil", price: 420, discountPrice: 395, unit: "500ml", stock: 14, isActive: true, isRnD: false, description_en: "Bold, naturally aromatic mustard oil made with careful cold pressing." },
  { id: "demo-mango-pickle", slug: "homestyle-mango-pickle", name_en: "Homestyle Mango Pickle", name_bn: "ঘরোয়া আমের আচার", category: "pickle", price: 330, unit: "350g", stock: 21, isActive: true, isRnD: false, description_en: "Tangy green mango, warming spices and a familiar homemade finish." },
  { id: "demo-garlic-paste", slug: "fresh-garlic-paste", name_en: "Fresh Garlic Paste", name_bn: "রসুন বাটা", category: "paste", price: 180, unit: "250g", stock: 16, isActive: true, isRnD: false, description_en: "Convenient, flavourful garlic paste for faster everyday meals." },
  { id: "demo-honey-drink", slug: "ginger-honey-drink", name_en: "Ginger Honey Drink", name_bn: "আদা মধু পানীয়", category: "drinks", price: 360, unit: "400ml", stock: 9, isActive: true, isRnD: false, description_en: "A bright, comforting blend of ginger and honey." },
  { id: "demo-marinade", slug: "smoky-bbq-marinade", name_en: "Smoky BBQ Marinade", name_bn: "স্মোকি বারবিকিউ মেরিনেড", category: "marinade", price: 285, unit: "300g", stock: 0, isActive: true, isRnD: false, description_en: "A balanced, savoury marinade for quick grills and roasts." },
  { id: "demo-rnd-coriander-paste", slug: "fresh-coriander-paste-rnd", name_en: "Fresh Coriander Paste — R&D Batch", name_bn: "ধনেপাতা বাটা — গবেষণা ব্যাচ", category: "paste", price: 210, unit: "250g", stock: 12, isActive: true, isRnD: true, description_en: "A limited small-batch coriander paste developed for bright, fresh everyday cooking." },
  { id: "demo-rnd-chilli-pickle", slug: "green-chilli-lime-pickle-rnd", name_en: "Green Chilli & Lime Pickle — R&D Batch", name_bn: "কাঁচামরিচ ও লেবুর আচার — গবেষণা ব্যাচ", category: "pickle", price: 295, unit: "300g", stock: 8, isActive: true, isRnD: true, description_en: "A lively limited-release pickle balancing fresh chilli heat with fragrant lime." },
];
